spring:
  datasource:
    url: jdbc:h2:~/rewardsdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8008
logging:
    level:
       root: INFO

